name: amazon_reviews
channels:
  - conda-forge
dependencies:
  - ipykernel
  - openpyxl
  - nodejs
  - numpy
  - pandas
  - pip
  - python
  - requests
  - Pillow
  - selenium
  - typing
  - tqdm
  - pip:
      - func_timeout
      - glob3
      - pickle-mixin
      - beautifulsoup4
      - lxml
